server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_server?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: EMBEDDED
      schema-locations: classpath:schema-mysql.sql
      data-locations: classpath:data.sql

logging:
  level:
    com.sg.auth.server: DEBUG